Restaurant.create!([
  {name: "Al's Pizza", cuisine: "Pizza", address: "1533 11th Ave, San Francisco, CA, 94122", phone: "415-123-4567", hours: "8am-8pm Daily", description: "Come enjoy a classic San Francisco pizza!  This delicious pizza is locally sourced, and free from GMOs, trans fats, gluten, carbs, and dairy."},
  {name: "Banchan Party", cuisine: "Korean", address: "1800 Divisadero St., San Francisco, CA, 94120", phone: "415-452-5645", hours: "10am-10pm Daily", description: "Tiny plates!  But lots of them."},
  {name: "Carr's", cuisine: "American", address: "1 First St, San Francisco, CA 94118", phone: "666-666-6666", hours: "10am-8pm Daily", description: "Serving up an American heritage cow"},
  {name: "Carl's Deli", cuisine: "Sandwiches", address: "94 Summer St., San Francisco, CA, 94117", phone: "415-879-1355", hours: "12pm-8pm Daily", description: "Our famous Heartstopper will... STOP YOUR HEART!"},
  {name: "Catch of the Century", cuisine: "Seafood", address: "93 Cantor St., San Francisco, CA, 94117", phone: "415-666-7948", hours: "12pm-8pm Daily", description: "Very clean seafood; no mercury!"},
  {name: "Chili Freeze", cuisine: "American", address: "1533 11th Ave, San Francisco, CA, 94120", phone: "415-128-9999", hours: "10am-8pm Daily", description: "Where else can you get chili ice cream?"},
  {name: "Garden of Delightful Breakfast Drinks", cuisine: "CoffeeandTea", address: "88 Hip Way, San Francisco, CA, 94116", phone: "415-197-4588", hours: "7am-6pm Daily", description: "We get you your fix and start your day off right."},
  {name: "Jade Palace", cuisine: "Chinese", address: "599 3rd St., San Francisco, CA, 94116", phone: "415-885-7922", hours: "10am-8pm Daily", description: "All delicious dishes served with NO MSG.  Seriously!"},
  {name: "Keyser Soze", cuisine: "Ramen", address: "344 Embarcadero One, San Francisco, CA, 94117", phone: "415-315-1411", hours: "12pm-8pm Daily", description: "Traditional Ramen with a criminal twist."},
  {name: "Manny's Meatloaf", cuisine: "American", address: "1234 7th St, San Francisco, CA, 94118", phone: "415-518-7348", hours: "M-F 8am-8pm; WKND 8am-12am", description: "Meatloaf done right: meaty, loafy... oh man!"},
  {name: "MaSu", cuisine: "Sushi", address: "123 Lonely Ave., San Francisco, CA, 94121", phone: "415-916-6653", hours: "12pm-11pm Daily", description: "Only the rawest of the raw fish!"},
  {name: "McDonald's", cuisine: "American", address: "553 Cowtown Blvd, San Francisco, CA, 94111", phone: "415-734-5666", hours: "7am-11pm Daily", description: "Over 1 billion served"},
  {name: "Mo's Vietnamese Kitchen", cuisine: "Vietnamese", address: "4811 Garber Ave., San Francisco, CA, 94121", phone: "415-888-4441", hours: "12pm-11pm Daily", description: "Serving a delicious taste of Vietnam since 1987."},
  {name: "The Oasis", cuisine: "Bars", address: "13 Elm St., San Francisco, CA 94119", phone: "415-822-8645", hours: "12pm-2am Daily", description: "A San Francisco classic, one of the original funky art on the walls places."},
  {name: "Pepito's Tacos", cuisine: "LatinAmerican", address: "1869 Carrerra Ave., San Francisco, CA, 94118", phone: "415-315-7815", hours: "10am-10pm Daily", description: "Breakfast, Burritos, Tacos, and more.  Try our signature salsas."},
  {name: "Raja", cuisine: "Indian", address: "2 Folsom St., San Francisco, CA, 94116", phone: "415-452-2233", hours: "10am-8pm Daily", description: "All your Indian favorites."},
  {name: "Shining Time Station", cuisine: "Bars", address: "4658 Pine St., San Francisco, CA 94124", phone: "415-223-6441", hours: "12pm-2am Daily", description: "Train themed adult beverages, complete with the Trainwreck singature drink made with filtered charcoal."},
  {name: "Thai Land", cuisine: "Thai", address: "2238 Clement St., San Francisco, CA, 94118", phone: "415-916-7945", hours: "12pm-10pm Daily", description: "Contains nuts.  Lots of nuts!"},
  {name: "Wok 'n' Roll", cuisine: "Chinese", address: "123 Grant St.", phone: "415-867-5309", hours: "9am - 8pm Daily", description: "Hello, welcome to Wok 'n' Roll!"}
])
Review.create!([
  {rev_content: "Ask for their secret Mongolian menu!", yepp: true, user_id: 2, restaurant_id: 19, username: "atheg"},
  {rev_content: "oooo!", yepp: true, user_id: 2, restaurant_id: 1, username: "joe"},
  {rev_content: "They served me green breadsticks!", yepp: false, user_id: 2, restaurant_id: 1, username: "atheg"},
  {rev_content: "The best pizza in town.", yepp: true, user_id: 2, restaurant_id: 1, username: "Guest"},
  {rev_content: "I didn't like it that much.", yepp: false, user_id: 2, restaurant_id: 16, username: "joe"},
  {rev_content: "The food wasn't very good and the owner was incredibly rude.", yepp: false, user_id: 3, restaurant_id: 19, username: "Guest"},
  {rev_content: "Yum!", yepp: true, user_id: 2, restaurant_id: 3, username: "atheg"},
  {rev_content: "Yuck!", yepp: false, user_id: 2, restaurant_id: 3, username: "Guest"},
  {rev_content: "BLARGLE!", yepp: false, user_id: 2, restaurant_id: 3, username: "joe"},
  {rev_content: "My favorite frozen chili in the whole wide world.", yepp: true, user_id: 4, restaurant_id: 6, username: "wendy"},
  {rev_content: "I wish they had more vegetarian options, though.", yepp: true, user_id: 4, restaurant_id: 8, username: "wendy"},
  {rev_content: "Not as good as Domino's, before they redid their whole pie.  Why mess with success, Domino's? WHY?", yepp: false, user_id: 4, restaurant_id: 1, username: "wendy"},
  {rev_content: "into it", yepp: true, user_id: 4, restaurant_id: 10, username: "wendy"},
  {rev_content: "I hate that they don't do breakfast all day.", yepp: false, user_id: 4, restaurant_id: 12, username: "wendy"},
  {rev_content: "This is old-timey deliciousness.", yepp: true, user_id: 4, restaurant_id: 3, username: "wendy"},
  {rev_content: "I never leave feeling like I had a bad time.", yepp: true, user_id: 4, restaurant_id: 14, username: "wendy"},
  {rev_content: "Naw, I'm just not that into trains.", yepp: false, user_id: 4, restaurant_id: 17, username: "wendy"},
  {rev_content: "They have the best honey walnut prawns in town.", yepp: true, user_id: 4, restaurant_id: 19, username: "wendy"},
  {rev_content: "I like their Jasmine latte!", yepp: true, user_id: 4, restaurant_id: 7, username: "wendy"},
  {rev_content: "Me and my roommate Tushar tried this place, but the delivery was late, and our order was cold by the time it arrived.", yepp: false, user_id: 4, restaurant_id: 16, username: "wendy"},
  {rev_content: "We got a bunch of things we didn't order...", yepp: false, user_id: 4, restaurant_id: 2, username: "wendy"},
  {rev_content: "Don't get the lengua -  they make theirs from tongue.", yepp: false, user_id: 4, restaurant_id: 15, username: "wendy"},
  {rev_content: "I'd steal something really big for a reservation here.  Best. Ramen. Ever.", yepp: true, user_id: 4, restaurant_id: 9, username: "wendy"},
  {rev_content: "Meh it's nothing special.", yepp: false, user_id: 4, restaurant_id: 4, username: "wendy"},
  {rev_content: "There was some mercury in mine.", yepp: false, user_id: 4, restaurant_id: 5, username: "wendy"},
  {rev_content: "Very cheap sake bombs.\n\nIf you're into that sort of thing.", yepp: true, user_id: 4, restaurant_id: 11, username: "wendy"},
  {rev_content: "I gave this to my 4 year old son, who has a very bad nut allergy.  He got hives.  Now I know he has a nut allergy.  More Thai Land for me!", yepp: true, user_id: 4, restaurant_id: 18, username: "wendy"},
  {rev_content: "These folks do Vietnamese coffee justice - so sweet and creamy!", yepp: true, user_id: 4, restaurant_id: 13, username: "wendy"},
  {rev_content: "Awesome meatball sub.", yepp: true, user_id: 3, restaurant_id: 4, username: "joe"},
  {rev_content: "wendy, that's disgusting.  Who wants cold chili?", yepp: false, user_id: 3, restaurant_id: 6, username: "joe"},
  {rev_content: "I like the octuple espresso breakfast combo.", yepp: true, user_id: 3, restaurant_id: 7, username: "joe"},
  {rev_content: "definitely had MSG.  I got a back cramp.  they're dishonest.  honestly, not sure how they stay in business if this is how they treat people.", yepp: false, user_id: 3, restaurant_id: 19, username: "joe"}
])
User.create!([
  {username: "Guest", password_digest: "$2a$10$s9NQzgIoYfwTPlq6Y7rmN.n/A/3SEa1EOEG5plhD9XPNODQCOEZcO", session_token: "+48S+2dnTIEVrj/WLLGDog=="},
  {username: "atheg", password_digest: "$2a$10$v9ovc6j0qYw9mFMltJOCau5SSR2mBI1geQUpMBYTUa6s0iPjuhlLG", session_token: "KfkmfR45aZoGgKi8m3dy4w=="},
  {username: "wendy", password_digest: "$2a$10$pHBXBgkbgMR/doOs3ByltOhm7.YyTh8QGT/xfcMUlalkOsXeuqKyi", session_token: "dVO6UY6zjsOUM/J3bqrleQ=="},
  {username: "joe", password_digest: "$2a$10$6hFB/kj3w9slUEaRMMYBUOAsRP1G4kmeCDNrtw5G6n4hDLGWdxBq2", session_token: "RoYDyilJbIKy0ANttNJXMA=="}
])
